Iter13
grafchitaru/shortener pull request #21
Opened 2024-01-17 11:02 UTC by grafchitaru

2024-01-19 21:46 UTC, bambruysk requested changes
Нужно поправить работу с контекстами

2024-01-19 21:46 UTC, bambruysk commented on docker/postgres/Dockerfile
> +    && apk del .debezium-build-deps
просто интересно а зачем нам в этом проекте debezium  и прочее?

2024-01-19 21:46 UTC, bambruysk commented on internal/handlers/createLinkBatch_test.go
> +	}
можно проще
assert.Equal(http.StatusCreated,rr.Code, "handler returned wrong status code")

2024-01-19 21:46 UTC, bambruysk commented on internal/handlers/createLinkBatch_test.go
> +	}
require.NoError(err)

2024-01-19 21:46 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	`).Scan(&exists)
если мы исполльзуем  IF NOT EXIST - ир зачем это?

2024-01-19 21:46 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	err = conn.QueryRow(context.Background(), `
лучше испольхзовать контекси с таймаутами

2024-01-19 21:46 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	tx, err := s.conn.Begin(context.Background())
нельзя ходить а базу с пустым  таймаутом

2024-01-19 21:46 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	tx, err := s.conn.Begin(context.Background())
контеекст нужно взять из запрса в хендлерах

2024-01-24 09:58 UTC, grafchitaru commented on docker/postgres/Dockerfile
> +    && apk del .debezium-build-deps
Да, забыл выпилить) Взял Docker постгресса с текущего проекта. Сейчас удалил, оставил чисто Postgres

2024-01-24 10:17 UTC, grafchitaru commented on internal/handlers/createLinkBatch_test.go
> +	}
Заменил

2024-01-24 10:27 UTC, grafchitaru commented on internal/handlers/createLinkBatch_test.go
> +	}
Поменял

2024-01-24 10:58 UTC, grafchitaru commented on internal/storage/postgresql/postgresql.go
> +	`).Scan(&exists)
Действительно, переписал запрос, добавил индекс в базовый запрос

2024-01-24 10:59 UTC, grafchitaru commented on internal/storage/postgresql/postgresql.go
> +	err = conn.QueryRow(context.Background(), `
Это вообще выпилил

2024-01-24 11:15 UTC, grafchitaru commented on internal/storage/postgresql/postgresql.go
> +	tx, err := s.conn.Begin(context.Background())
Поправил

2024-01-26 15:40 UTC, bambruysk approved these changes
Принято

2024-01-31 07:50 UTC, merged