Iter15
grafchitaru/shortener pull request #23
Opened 2024-02-05 14:31 UTC by grafchitaru

2024-02-07 14:26 UTC, bambruysk requested changes
С куками хорошо, а вот с асинхронным удалением надо доработать

2024-02-07 14:26 UTC, bambruysk commented on internal/auth/auth.go
> +	return claims["user_id"].(string), nil
здесь потенциальная паника так как там может быть в общем случае не string
Используй userID, ok := claims["user_id"].(string)

2024-02-07 14:26 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	resultChannel := make(chan bool, len(deleteIDs))
здесь лучше использовать канал пустых структур или ошибок

2024-02-07 14:26 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	for i := 0; i < len(deleteIDs); i++ {
здесь получается все равно синхронный запрос, так как мы дожидаемся удаления всех урлов и получается вся эта возня с горутинами теряет смысл. 

Начало в целом верное мы берем в горутине и записываем данные в канал. Дальше в другой горутине собираем нужное количество ( выбор на усмотрение, можно в конфиге задать) в батч и отправляем в БД

При этом необходимо, чтобы батчи собирались нужного размера, не накапливались слишком долго ( таймаут) 

то есть схема такая  множество горутин запросов пишут в один канал. Из этого канала воркер считывает данные ( и url и userID) и отправляет в батч

2024-02-07 14:26 UTC, bambruysk commented on internal/storage/sqlite/sqlite.go
> +		// process rows here
Но обрабатывается?

2024-02-09 12:57 UTC, grafchitaru commented on internal/auth/auth.go
> +	return claims["user_id"].(string), nil
Поправил

2024-02-09 13:00 UTC, grafchitaru commented on internal/storage/postgresql/postgresql.go
> +	for i := 0; i < len(deleteIDs); i++ {
Поправил

2024-02-09 13:01 UTC, grafchitaru commented on internal/storage/sqlite/sqlite.go
> +		// process rows here
Поправил

2024-02-10 08:55 UTC, bambruysk requested changes
Нужно доработать асинхронное удаление

2024-02-10 08:55 UTC, bambruysk commented on internal/handlers/deleteUserUrls.go
> +	}
Ты вызываешь эту функцию - а она дожидается результатов удаления, Асинхронно все равно пока не получилось.

Давай на следующе неделе 1x1 созвонимся и обсудим этот момент.

2024-02-11 05:23 UTC, grafchitaru commented on internal/handlers/deleteUserUrls.go
> +	}
Давай созвонимся, ок. Я внес правку, сделал вызов ассинхронным

2024-02-13 07:14 UTC, bambruysk approved these changes
Принято

2024-02-13 07:14 UTC, bambruysk commented on internal/handlers/deleteUserUrls.go
> +			http.Error(res, err.Error(), http.StatusBadRequest)
к этому моменту хенддлер уже закроется и обработка закончится - так что отправлять BadRequest  будет некому. Так что надо просто залогировать ошибку

Здесь лучше сделать запись в канал, и с другой стороны его вычитывать.  Формально у нас сейчас асинхронный режим, конечно) Хотя и не совсем такой какой бы хотелось.

2024-02-19 14:50 UTC, merged